project:
  type: website
  output-dir: docs

website:
  page-navigation: true
  title: "Econ 148"
  favicon: "plot/econ148-hex-logo.png"
  
  repo-url: https://github.com/econ148-analytical-stat-package
  site-url: https://econ148-analytical-stat-package.github.io/econ148-site/
  
  sidebar:
    style: docked
    pinned: true
    seacrh: true
    logo: "plot/econ148-hex-logo.png"
    contents:
      - href: "index.qmd"
        text: "Home"
      - section: "Topics"
        contents:
          - href: "m1-intro-r.qmd"
            text: "Module 1: Introduction to R programming"
          - href: "m2-intro-data-viz-ggplot.qmd"
            text: "Module 2: Intro to data visualization using ggplot2"
          - href: ""
            text: "Module 3: Reproducible report with Quarto in R"
          - href: ""
            text: "Module 4: survey research design"
          - href: ""
            text: "Module 5: exploratory data analysis"
          - href: ""
            text: "Module 6: test on means"
          - href: ""
            text: "Module 7: correlation and regression analysis"
          - href: ""
            text: "Module 8: limited-dependent variable models"
          - href: ""
            text: "Module 9: Exploratory factor analysis (EFA)"
      - section: "Assignment"
        contents:
          - href: "01-assignment-1-e-commerce.qmd"
            text: "Module 1 assignment"
      - section: "Midterm & Final projects"
        contents:
          - href: "term-01-midterm-project.qmd"
            text: "Midterm project: Earthquake and tsunami analysis"
          

format:
  html:
    theme:
      light: [cosmo, styles.scss]
      dark: [cosmo, dark-style.scss]
    mainfont: "Arial"
    code-copy: true
    code-overflow: wrap
    toc: true

freeze: auto
editor: visual

